development:
  omniauth_facebook_id: 1082860905880932
  omniauth_facebook_secret: ca3c9e2924ec55b0855b2cde9f8a05ce
  omniauth_vkontakte_id: 8072303
  omniauth_vkontakte_secret: j3skbJjL74DI7Z0e8LYZ

production:
  omniauth_facebook_id: 1082860905880932
  omniauth_facebook_secret: ca3c9e2924ec55b0855b2cde9f8a05ce
  omniauth_vkontakte_id: 8072303
  omniauth_vkontakte_secret: j3skbJjL74DI7Z0e8LYZ
